# ==========================================
# [MITM / 主机名配置]
# 仅需抓取负责下发界面布局配置的域名
hostname = app.bilibili.com

# ==========================================
# [重写规则 / Rewrite_Local]
# 拦截底部 Tab 和顶部 Tab 的布局配置接口，交由本地脚本处理
^https?:\/\/app\.bilibili\.com\/x\/resource\/show\/tab url script-response-body https://m6506659306.github.io/QX/clearbili.js
