# ==========================================
# [MITM / 主机名配置]
# 仅需抓取负责下发界面布局配置的域名
hostname = manga.bilibili.com, api.live.bilibili.com, api.vc.bilibili.com, app.bilibili.com, app.biliapi.net, api.bilibili.com, api.biliapi.net, grpc.biliapi.net
# ==========================================
# [重写规则 / Rewrite_Local]
# 拦截底部 Tab 和顶部 Tab 的布局配置接口，交由本地脚本处理
^https?:\/\/app\.bilibili\.com\/x\/resource\/show\/tab url script-response-body https://m6506659306.github.io/QX/clearbili.js
# 去除搜索中的默认关键词
^https?:\/\/(grpc|app)\.bili(bili\.com|api\.net)\/bilibili\.app\.interface\.v1\.Search\/DefaultWords$ url reject
# 去除搜索中的大家都在搜
^https?:\/\/api\.vc\.bilibili\.com\/search_svr\/v\d\/Search\/recommend_words url reject-dict
# 去除动态中的话题
^https?:\/\/api\.vc\.bilibili\.com\/topic_svr\/v1\/topic_svr url reject-dict
# 去除动态中的最常访问
^https?:\/\/api\.vc\.bilibili\.com\/dynamic_svr\/v1\/dynamic_svr\/mix_uplist url reject-dict
